spring:
  data:
    mongodb:
      uri: mongodb+srv://Reddyvr03:hLcDn9y9qhHGAXXB@cluster0.coi4m2z.mongodb.net/?appName=Cluster0
      database: journaldb
      auto-index-creation: true
  redis:
    url: redis://default:FnfrmJ8syh9aHYRYMDeL8FrwadgrA2Qe@recess-vertical-title-34647.db.redis.io:17635
  mail:
    host: smtp.gmail.com
    port: 587
    username: karthikswapnareddy@gmail.com
    password: uwsy nzhw zgqw mvhi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    bootstrap-servers: pkc-9q8rv.ap-south-2.aws.confluent.cloud:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: weekly-sentiment-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: net.engineeringdigest.journalApp.model
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: PLAIN
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username='OJ36O3ZNX2L2V2IB' password='cfltZ2xNahET4H4Uy/RUmmAq/loIPv58xgETgYeW2XX43NnHvWO0rDyGqjJJp7LQ';
      session:
        timeout:
          ms: 45000
logging:
  level:
    net:
      engineeringdigest:
        journalApp: TRACE

weather_api_key: "763a11fd003633594b4ca216c05a75c4"
#logging:
#  level:
#    root:DEBUG